tools: check if .git/modules exists in install-deps
Check if the modules were initialized as a last step in install-deps. If
not, provide the user with a tip to initialize them.

BUG=N/A
TEST=clone crosvm. run install-deps. Check error. initialize submodules.
Run install-deps, no error.

Change-Id: I2d0de669a2c5a17e8e6f5a7343f28bbe9b564c07
Reviewed-on: https://chromium-review.googlesource.com/c/crosvm/crosvm/+/6004400
Reviewed-by: Dennis Kempin <denniskempin@google.com>
Commit-Queue: Elie Kheirallah <khei@google.com>
Reviewed-by: Daniel Verkamp <dverkamp@chromium.org>

diff --git a/tools/install-deps b/tools/install-deps
--- a/tools/install-deps
+++ b/tools/install-deps
@@ -101,3 +101,11 @@ cargo binstall --no-confirm mdbook-linkcheck --version "0.7.7"
 
 # Nextest is an improved test runner for cargo
 cargo binstall --no-confirm cargo-nextest --version "0.9.49"
+
+Red='\033[0;31m'
+Reset='\033[0m'
+# Check if submodules were initialized. If a submodule is not initialized, git
+# submodule status will be prefixed with `-`
+if git submodule status | grep '^-'; then
+    >&2 echo -e "${Red}ERROR${Reset}: Git modules were not initialized. Run 'git submodule update --init' to initialize them."
+fi
